name: ttproj
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.2.0
  dio: ^5.9.0
  shared_preferences: ^2.5.3
  data_connection_checker_tv: ^0.3.5-nullsafety
  flutter_bloc: ^9.1.1
  bloc: ^9.1.0
  meta: ^1.16.0
  get_it: ^9.0.5
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  skeletonizer: ^2.1.0+1
  lottie: ^3.3.2
  go_router: ^17.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7

flutter_native_splash:
  color: "#ffffff"
  image: assets/images/on_boarding/Pattern.jpg
  android: true
  ios: true

  android_12:
    color: "#ff ffff"
    image: assets/images/on_boarding/Pattern.jpg

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/images/splash_screen/
    - assets/images/on_boarding/
    - assets/images/authentication/
    - assets/images/animation/
  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/SFProText/SF-Pro-Text-Light.otf
          weight: 300
        - asset: assets/fonts/SFProText/SF-Pro-Text-Regular.otf
          weight: 400
        - asset: assets/fonts/SFProText/SF-Pro-Text-Medium.otf
          weight: 500
        - asset: assets/fonts/SFProText/SF-Pro-Text-Semibold.otf
          weight: 600
        - asset: assets/fonts/SFProText/SF-Pro-Text-Bold.otf
          weight: 700
        - asset: assets/fonts/SFProText/SF-Pro-Text-Heavy.otf
          weight: 800
